name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 16.171.38.41
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            cd ~/online_chess
            git pull origin main

            cd ~/online_chess/front-end
            npm install
            npm run build
            sudo rm -rf /var/www/chess/*
            sudo cp -r build/* /var/www/chess/
            sudo systemctl reload nginx

            cd ~/online_chess/back-end
            source venv/bin/activate
            pip install -r requirements.txt

            cd ~/online_chess/stockfish_bots/stock-17/Stockfish/src
            make -j4 build ARCH=x86-64-sse41-popcnt || true

            sudo systemctl restart chess
